version: "3.9"
services:
  nginx:
    container_name: keix-nginx
    build:
      context: ${NGINX}
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes:
      - ${NGINX}/html:/usr/share/nginx/html
      - ${NGINX}/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  uvicorn:
    container_name: keix-uvicorn
    build:
      context: ${UVICORN}
      dockerfile: Dockerfile
    volumes:
      - ${UVICORN}/app:/code/app
    networks:
      - default

networks:
  default:
    name: ${NETWORK}
